from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):
    initial = True
    dependencies = [('auth','0012_alter_user_first_name_max_length')]
    operations = [
        migrations.CreateModel(name='Department',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('name',models.CharField(max_length=120,unique=True)),('code',models.CharField(max_length=20,unique=True))]),
        migrations.CreateModel(name='TeacherProfile',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('employee_id',models.CharField(max_length=40,unique=True)),('email',models.EmailField(max_length=254)),('designation',models.CharField(blank=True,max_length=100)),('phone',models.CharField(blank=True,max_length=20)),('status',models.CharField(choices=[('PENDING','Pending'),('APPROVED','Approved'),('REJECTED','Rejected')],default='PENDING',max_length=10)),('department',models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.SET_NULL,related_name='teachers',to='campus.department')),('user',models.OneToOneField(on_delete=django.db.models.deletion.CASCADE,related_name='teacher_profile',to='auth.user'))]),
        migrations.CreateModel(name='Classroom',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('name',models.CharField(max_length=100)),('year',models.CharField(max_length=20)),('section',models.CharField(max_length=10)),('academic_year',models.CharField(default='2026-2027',max_length=20)),('room_number',models.CharField(blank=True,max_length=40)),('capacity',models.PositiveIntegerField(default=65)),('active',models.BooleanField(default=True)),('department',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='classrooms',to='campus.department')),('teacher_one',models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.SET_NULL,related_name='classrooms_one',to='campus.teacherprofile')),('teacher_two',models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.SET_NULL,related_name='classrooms_two',to='campus.teacherprofile'))]),
        migrations.CreateModel(name='StudentProfile',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('register_number',models.CharField(max_length=30,unique=True)),('email',models.EmailField(max_length=254)),('college',models.CharField(blank=True,max_length=180)),('year',models.CharField(blank=True,max_length=20)),('section',models.CharField(blank=True,max_length=10)),('phone',models.CharField(blank=True,max_length=20)),('cgpa',models.DecimalField(decimal_places=2,default=0,max_digits=4)),('status',models.CharField(choices=[('PENDING','Pending'),('APPROVED','Approved'),('REJECTED','Rejected'),('BLOCKED','Blocked')],default='PENDING',max_length=10)),('classroom',models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.SET_NULL,related_name='students',to='campus.classroom')),('department',models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.SET_NULL,related_name='students',to='campus.department')),('user',models.OneToOneField(on_delete=django.db.models.deletion.CASCADE,related_name='student_profile',to='auth.user'))]),
        migrations.CreateModel(name='Subject',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('code',models.CharField(max_length=20,unique=True)),('name',models.CharField(max_length=160)),('credits',models.PositiveIntegerField(default=3)),('semester',models.PositiveIntegerField(default=5)),('department',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='subjects',to='campus.department'))]),
        migrations.CreateModel(name='Achievement',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('title',models.CharField(max_length=180)),('issuer',models.CharField(blank=True,max_length=160)),('date',models.DateField(blank=True,null=True)),('description',models.TextField(blank=True)),('student',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='achievements',to='campus.studentprofile'))]),
        migrations.CreateModel(name='Project',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('title',models.CharField(max_length=180)),('description',models.TextField(blank=True)),('tech_stack',models.CharField(blank=True,max_length=250)),('link',models.URLField(blank=True)),('status',models.CharField(default='In Progress',max_length=40)),('created_at',models.DateTimeField(auto_now_add=True)),('student',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='projects',to='campus.studentprofile'))]),
        migrations.CreateModel(name='LeaveRequest',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('from_date',models.DateField()),('to_date',models.DateField()),('reason',models.CharField(max_length=200)),('description',models.TextField(blank=True)),('status',models.CharField(choices=[('PENDING','Pending'),('APPROVED','Approved'),('REJECTED','Rejected')],default='PENDING',max_length=10)),('created_at',models.DateTimeField(auto_now_add=True)),('reviewed_by',models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.SET_NULL,to='campus.teacherprofile')),('student',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='leave_requests',to='campus.studentprofile'))]),
        migrations.CreateModel(name='Mark',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('internal',models.PositiveIntegerField(default=0)),('external',models.PositiveIntegerField(default=0)),('updated_at',models.DateTimeField(auto_now=True)),('student',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='marks',to='campus.studentprofile')),('subject',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='marks',to='campus.subject'))]),
        migrations.AddConstraint(model_name='mark',constraint=models.UniqueConstraint(fields=('student','subject'),name='unique_student_subject_mark')),
        migrations.CreateModel(name='Attendance',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('date',models.DateField()),('status',models.CharField(choices=[('P','Present'),('A','Absent'),('L','Leave')],default='P',max_length=1)),('created_at',models.DateTimeField(auto_now_add=True)),('student',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='attendance_records',to='campus.studentprofile')),('subject',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='attendance_records',to='campus.subject')),('teacher',models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.SET_NULL,related_name='attendance_records',to='campus.teacherprofile'))]),
        migrations.AddConstraint(model_name='attendance',constraint=models.UniqueConstraint(fields=('student','subject','date'),name='unique_daily_attendance')),
        migrations.CreateModel(name='TimetableEntry',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('day',models.CharField(choices=[('MON','Monday'),('TUE','Tuesday'),('WED','Wednesday'),('THU','Thursday'),('FRI','Friday'),('SAT','Saturday')],max_length=3)),('period',models.PositiveIntegerField(default=1)),('time',models.CharField(default='09:00 - 10:00',max_length=40)),('custom_subject',models.CharField(blank=True,max_length=160)),('room',models.CharField(blank=True,max_length=40)),('faculty',models.CharField(blank=True,max_length=120)),('classroom',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='timetable',to='campus.classroom')),('subject',models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.SET_NULL,related_name='timetable_entries',to='campus.subject'))]),
        migrations.AddConstraint(model_name='timetableentry',constraint=models.UniqueConstraint(fields=('classroom','day','period'),name='unique_classroom_day_period')),
        migrations.CreateModel(name='AuditLog',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('action',models.CharField(max_length=120)),('object_type',models.CharField(max_length=120)),('object_id',models.CharField(blank=True,max_length=50)),('created_at',models.DateTimeField(auto_now_add=True)),('actor',models.ForeignKey(null=True,on_delete=django.db.models.deletion.SET_NULL,to='auth.user'))]),
    ]
