# Generated by Django 6.1 on 2026-09-06 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("campus", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="attendance",
            options={"ordering": ["-date"]},
        ),
        migrations.AlterModelOptions(
            name="timetableentry",
            options={"ordering": ["day", "period"]},
        ),
    ]
